config/routes.rb
TellServer::Application.routes.draw do
  resources :feeds

  root to: 'pages#index'
  get '/download', to: 'pages#download'
  get '/app',      to: 'pages#download'

  get '/privacy', to: 'pages#privacy'

  devise_for :users, :controllers => { :registrations => "registrations" }

  get '/users/profile', to: 'users#profile'
  put '/users/facebook', to: 'social#facebook'
  put '/users/photo_select', to: 'social#photo_select'

  resources :users, except: [:new, :create] do
    resources :messages, except: [:new]
    collection do
      post :alert
      put :leave
    end
    member do
      post :invite
    end
  end
  resources :versions
  resources :locations do
    resources :attendees, only: :index
  end
  put 'locations/:location_id/attendees', to: 'attendees#attend'
  delete 'locations/:location_id/attendees', to: 'attendees#leave'

  get 'metrics', to: 'metrics#index'


  resources :notifications, only: [:index, :destroy]

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  self.inheritance_column = :pomelo_rocks
  has_and_belongs_to_many :users
  validates_presence_of :type
  default_scope { order('id DESC') }
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  load_and_authorize_resource
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @feeds = Feed.all
    respond_with(@feeds)
  end

  def show
    respond_with(@feed)
  end

  def new
    @feed = Feed.new
    respond_with(@feed)
  end

  def edit
  end

  def create
    @feed = Feed.new(feed_params)
    @feed.save
    respond_with(@feed)
  end

  def update
    @feed.update(feed_params)
    respond_with(@feed)
  end

  def destroy
    @feed.destroy
    respond_with(@feed)
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:title, :detail, :action, :type, {user_ids: []})
    end
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title, cols: 30, rows: 3 %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail, cols: 60, rows: 3 %>
  </div>
  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %> Eg /locations/14
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.select(:type, options_for_select(['message', 'users'], @feed.type)) %>
  </div>
  <div class="users field">
    <%= f.label :users %><br>
    <%=collection_check_boxes(:feed, :user_ids, User.all, :id, :username)%>
  </div>
  <div>Count: <em id="counter"></em></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table class="table">
  <thead>
    <tr>
      <th>Created at</th>
      <th>Title</th>
      <th>Detail</th>
      <th>Action</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.created_at %></td>
        <td><%= feed.title %></td>
        <td><%= feed.detail %></td>
        <td><%= feed.action %></td>
        <td><%= feed.type %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @feed.detail %>
</p>

<p>
  <strong>Action:</strong>
  <%= @feed.action %>
</p>

<p>
  <strong>Type:</strong>
  <%= @feed.type %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>