config/routes.rb
TellServer::Application.routes.draw do
  resources :feeds

  root to: 'pages#index'
  get '/download', to: 'pages#download'
  get '/app',      to: 'pages#download'

  get '/privacy', to: 'pages#privacy'

  devise_for :users, :controllers => { :registrations => "registrations" }

  get '/users/profile', to: 'users#profile'
  put '/users/facebook', to: 'social#facebook'
  put '/users/photo_select', to: 'social#photo_select'

  resources :users, except: [:new, :create] do
    resources :messages, except: [:new]
    collection do
      post :alert
      put :leave
    end
    member do
      post :invite
    end
  end
  resources :versions
  resources :locations do
    resources :attendees, only: :index
  end
  put 'locations/:location_id/attendees', to: 'attendees#attend'
  delete 'locations/:location_id/attendees', to: 'attendees#leave'

  get 'metrics', to: 'metrics#index'


  resources :notifications, only: [:index, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :ensure_authentication_token

  include ApplicationHelper

  has_attached_file :picture, :styles => { medium: '320x320#', thumb: '160x160#', icon: '50x50#' }, :default_url => "/images/user_missing_:style.png"
  has_many :identities, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :user_photos, dependent: :destroy
  has_many :received_messages, class_name: "Message", foreign_key: "to_id", dependent: :destroy
  has_many :notifications, foreign_key: "to_id"
  belongs_to :location, inverse_of: :attendees

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  validates_inclusion_of :gender, in: ['male', 'female'], allow_blank: true

  scope :real, -> { where(fake: false) }
  scope :male, -> { where(gender: 'male') }
  scope :female, -> { where(gender: 'female') }


  def to_s
    username
  end

  def notify attributes
    notifications.where(from_id: attributes[:from].id, type: attributes[:type]).destroy_all
    notification = notifications.create(attributes)
    if device_token.present? && notification.unread
      GCM.send_notification device_token, {
        id: notification.id,
        title: notification.title,
        message: notification.text,
        type: notification.type,
        from_id:       notification.from.id,
        from_username: notification.from.username,
        from_thumb:    absolute_url(notification.from.picture(:icon)),
        read: notification.read,
        msgcnt: notifications.unread.count
      }
    end
    notification
  end

private

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = Devise.friendly_token
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy, :invite]

  # GET /users
  # GET /users.json
  def index
    if params[:version_id].present?
      @users = Version.find(params[:version_id]).events.registration.map(&:user)
    else
      @users = User.paginate(:page => params[:page])
    end
    @versions = Version.all

    if params[:commit] == 'Export'
      render xlsx: 'index', filename: "users-#{Time.zone.now}.xlsx"
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    current_user.notifications.where(from: @user, type: 'invite').update_all(read: true)
    @invited = Notification.where(from: current_user, to: @user, type: 'invite').count > 0
  end

  # GET /users/new
  def new
    @user = User.new
    @locations = Location.all
  end

  # GET /users/1/edit
  def edit
    @locations = Location.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def invite
    @user.notify(
      from:  current_user,
      text:  "Te invitó un trago.",
      title: "#{current_user}",
      type:  "invite")

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully notified.' }
      format.json { head :no_content }
    end
  end

  def profile
    @user = current_user
    @feeds = Feed.all
  end

  def alert
    User.where(location_id: nil).find_each do |user|
      send_system_notification user, "Warmapp", "#{user.username}! A donde salis esta noche?"
    end
    redirect_to users_path
  end

  def leave
    User.update_all(location_id: nil)
    @locations = Location.all
    redirect_to users_path
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :email, :password, :picture, :admin, :fake, :gender, :device_token, :birthday, :location_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def send_system_notification(user, title, text)
    if user.device_token.present?
      GCM.send_notification user.device_token, {
        title: title,
        message: text,
        type: 'system'
      }
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.text_field :birthday %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :device_token %><br>
    <%= f.text_field :device_token %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="field">
    <%= f.label :fake %><br>
    <%= f.check_box :fake %>
  </div>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.select :location_id, options_from_collection_for_select(@locations, "id", "name"), include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= form_tag(:users, method: :get, class: 'search-box') do %>
  <%= label_tag :version %>
  <%= select_tag :version_id, options_for_select(@versions.collect {|p| [ p.name, p.id ] }, params[:version_id]), :prompt => "All" %>
  <%= submit_tag "Export", class: 'btn btn-secondary pull-right' %>
  <%= submit_tag "Search", class: 'btn btn-primary pull-right' %>
<% end %>

<%= will_paginate @users if @users.respond_to?(:total_pages) %>
<table class="table">
  <thead>
    <tr>
      <th>Picture</th>
      <th>Username</th>
      <th>Email</th>
      <th>Attending to</th>
      <th>Social IDs</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr admin=<%=user.admin %> >
        <td><%= image_tag(user.picture.url(:thumb)) %></td>
        <td class="id"><%= user.username %></td>
        <td class="id"><%= user.email %></td>
        <td><%= user.location %></td>
        <td><%= user.identities.map(&:provider).join(', ') %></td>
        <td><%= link_to 'Invite', invite_user_path(user), method: :post %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @users if @users.respond_to?(:total_pages) %>
<div class="collection-actions">
  <%= button_to 'Leave',  { action: 'leave' }, { method: 'put',  data: { confirm:'All the users will leave they place' }, class: 'btn btn-primary pull-right' } %>
  <%= button_to 'Alert',  { action: 'alert' }, { method: 'post', data: { confirm:'All the users will receive a push notification' }, class: 'btn btn-primary pull-right' } %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag(@user.picture.url(:medium)) %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong>Fake:</strong>
  <%= @user.fake %>
</p>

<% if @user.identities.any? %>
  <p>
    <strong>Profile:</strong>
    <%= link_to 'link', 'http://facebook.com/' + @user.identities.first.uid, target: '_blank' %>
  </p>
<% end %>

<p>
  <strong>Events:</strong>
  <ul>
    <% @user.events.each do |event| %>
      <li><%= event.event_type %></li>
    <% end%>
  </ul>

</p>

<p>
  <strong>Completed tutorial:</strong>
  <%= @user.completed_tutorial %>
</p>

<p>
  <strong>Attending to:</strong>
  <%= @user.location %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Messages', user_messages_path(@user) %> |
<%= link_to 'Back', users_path %>