config/routes.rb
TellServer::Application.routes.draw do
  resources :feeds

  root to: 'pages#index'
  get '/download', to: 'pages#download'
  get '/app',      to: 'pages#download'

  get '/privacy', to: 'pages#privacy'

  devise_for :users, :controllers => { :registrations => "registrations" }

  get '/users/profile', to: 'users#profile'
  put '/users/facebook', to: 'social#facebook'
  put '/users/photo_select', to: 'social#photo_select'

  resources :users, except: [:new, :create] do
    resources :messages, except: [:new]
    collection do
      post :alert
      put :leave
    end
    member do
      post :invite
    end
  end
  resources :versions
  resources :locations do
    resources :attendees, only: :index
  end
  put 'locations/:location_id/attendees', to: 'attendees#attend'
  delete 'locations/:location_id/attendees', to: 'attendees#leave'

  get 'metrics', to: 'metrics#index'


  resources :notifications, only: [:index, :destroy]

end

app/models/version.rb
class Version < ActiveRecord::Base
  validates_presence_of :name

  def events
    events_without_user.joins(:user).where("users.admin" => false).where("users.created_at >= ?", created_at)
  end

  def events_without_user
    events_without_user = Event.where("events.created_at >= ?", created_at)
    if next_version.nil?
      events_without_user
    else
      events_without_user.where('events.created_at < ?', next_version.created_at)
    end
  end

  def events_for event_type
    if event_type == 'landing'
      events_without_user.where(event_type: 'landing')
    else
      events.where(event_type: event_type)
    end
  end

  def number_of_users
    if has_landing
      events_without_user.landing.count
    else
      events.registration.count
    end
  end

  def days_online
    if next_version.nil?
      (Time.zone.now.to_date - created_at.to_date).to_i
    else
      (next_version.created_at.to_date - created_at.to_date).to_i
    end
  end

private

  def next_version
    Version.where('id > ?', id).first
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  load_and_authorize_resource
  before_action :set_version, only: [:show, :edit, :update, :destroy]

  # GET /versions
  # GET /versions.json
  def index
    @versions = Version.all
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
  end

  # GET /versions/1/edit
  def edit
  end

  # POST /versions
  # POST /versions.json
  def create
    @version = Version.new(version_params)

    respond_to do |format|
      if @version.save
        format.html { redirect_to @version, notice: 'Version was successfully created.' }
        format.json { render :show, status: :created, location: @version }
      else
        format.html { render :new }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /versions/1
  # PATCH/PUT /versions/1.json
  def update
    respond_to do |format|
      if @version.update(version_params)
        format.html { redirect_to @version, notice: 'Version was successfully updated.' }
        format.json { render :show, status: :ok, location: @version }
      else
        format.html { render :edit }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @version.destroy
    respond_to do |format|
      format.html { redirect_to versions_url, notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params.require(:version).permit(:name, :release_date, :hipotesis, :blog_url, :version_number, :created_at, :has_landing)
    end
end

app/views/versions/_form.html.erb
<%= form_for(@version) do |f| %>
  <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :version_number %><br>
    <%= f.text_field :version_number %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.text_field :created_at %>
  </div>
  <div class="field">
    <%= f.label :hipotesis %><br>
    <%= f.text_area :hipotesis %>
  </div>
  <div class="field">
    <%= f.label :blog_url %><br>
    <%= f.text_field :blog_url %>
  </div>
  <div class="field">
    <%= f.label :has_landing %><br>
    <%= f.check_box :has_landing %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/versions/edit.html.erb
<h1>Editing version</h1>

<%= render 'form' %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', versions_path %>

app/views/versions/index.html.erb
<h1>Listing versions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Release date</th>
      <th>Name</th>
      <th>Number of users</th>
      <th>Days online</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= version.created_at %></td>
        <td><%= version.name %></td>
        <td><%= version.number_of_users %></td>
        <td><%= version.days_online %></td>
        <td><%= link_to 'Blog post', version.blog_url, target: '_blank' if version.blog_url.present? %></td>
        <td><%= link_to 'Show', version %></td>
        <td><%= link_to 'Edit', edit_version_path(version) %></td>
        <td><%= link_to 'Destroy', version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Version', new_version_path %>

app/views/versions/new.html.erb
<h1>New version</h1>

<%= render 'form' %>

<%= link_to 'Back', versions_path %>

app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @version.name %>
</p>

<p>
  <strong>Version number:</strong>
  <%= @version.version_number %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @version.created_at %>
</p>

<p>
  <strong>Hipotesis:</strong>
  <%= @version.hipotesis %>
</p>

<p>
  <strong>Blog url:</strong>
  <%= @version.blog_url %>
</p>

<p>
  <strong>Total users:</strong>
  <%= @version.number_of_users %>
</p>

<%= link_to 'Edit', edit_version_path(@version) %> |
<%= link_to 'Back', versions_path %>