config/routes.rb
TellServer::Application.routes.draw do
  resources :feeds

  root to: 'pages#index'
  get '/download', to: 'pages#download'
  get '/app',      to: 'pages#download'

  get '/privacy', to: 'pages#privacy'

  devise_for :users, :controllers => { :registrations => "registrations" }

  get '/users/profile', to: 'users#profile'
  put '/users/facebook', to: 'social#facebook'
  put '/users/photo_select', to: 'social#photo_select'

  resources :users, except: [:new, :create] do
    resources :messages, except: [:new]
    collection do
      post :alert
      put :leave
    end
    member do
      post :invite
    end
  end
  resources :versions
  resources :locations do
    resources :attendees, only: :index
  end
  put 'locations/:location_id/attendees', to: 'attendees#attend'
  delete 'locations/:location_id/attendees', to: 'attendees#leave'

  get 'metrics', to: 'metrics#index'


  resources :notifications, only: [:index, :destroy]

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :attendees, class_name: "User", inverse_of: :location

  has_attached_file :photo, styles: { medium: "400>x200", thumb: "100x100>" }, :default_url => "/images/location_missing_:style.jpg"
  has_attached_file :banner, :styles => { :medium => "600x300!" }

  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  default_scope { order('relevance desc') }
  def to_s
    name
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  load_and_authorize_resource
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    if params['name'].present?
      priority = @locations.where("name like :name or alternative_name like :name", name: "%#{params['name']}%").limit(5)
      other_results = Location.where('description like :name or address like :name ', name: "%#{params['name']}%").limit(10)
      other_results = other_results.reject{ |l| priority.include? l }

      @locations = priority.concat(other_results)
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  def attend
    current_user.location = @location
    current_user.save!
    respond_to do |format|
      format.html { redirect_to @location, notice: 'You are going!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :alternative_name, :address, :phone, :photo, :banner, :description, :capacity, :relevance)
    end
end

app/views/locations/_form.html.erb
<%= form_for(@location, multipart: true) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :alternative_name %><br>
    <%= f.text_field :alternative_name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :banner %><br>
    <%= f.file_field :banner %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "40x10" %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.text_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :relevance %><br>
    <%= f.text_field :relevance %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn btn-success" %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Description</th>
      <th>Relevance</th>
      <th>Photo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.address %></td>
        <td><%= location.description %></td>
        <td><%= location.relevance %></td>
        <td><%= image_tag(location.photo.url(:thumb)) %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Thumb:</strong><br/>
  <%= image_tag(@location.photo.url(:thumb)) %>
</p>
<p>
  <strong>Banner:</strong><br/>
  <%= image_tag(@location.banner.url(:medium)) %>
</p>
<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Alternative name:</strong>
  <%= @location.alternative_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @location.phone %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format @location.description %>
</p>

<p>
  <strong>Relevance:</strong>
  <%= @location.relevance %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'See attendees', location_attendees_path(@location) %> |
<%= link_to 'Back', locations_path %>